### ISSUE TITLE
Improve Routing Meathod to allow for future expansion.

### ISSUE THREAD

**Issue by Curtis-Thomas** [Curtis-Thomas/free-api-list-with-react#10]
Review and update the current routing method to allow for future growth.

**Comment by pchawlaji** [comment]
Hi @Curtis-Thomas, Kindly assign this issue to me.

**Comment by Curtis-Thomas** [comment]
I'm away from my screen for a while, but I will have a look as soon as I'm back online :)

**Comment by pchawlaji** [comment]
Hi @Curtis-Thomas,
Hope you are doing great. Did you had a chance to review the PR. Would love to hear back a seek some feedback on any short comings. Thank you for your time.
