### ISSUE TITLE
In the CardRouting component, When the title is a bit long it overlaps with the tags and the description 

### ISSUE THREAD

**Issue by Abhay-Narayan** [Curtis-Thomas/free-api-list-with-react#119]
In the CardRouting component, When the title is a bit long it overlaps with the tags and the description, making it look unresponsive

Expected Behavior
All the content should be properly aligned

Steps to Reproduce (if applicable)
Checkout this temporary deployment - https://deploy-preview-117--tangerine-seahorse-5cf0e7.netlify.app/GeocodingDash for more details.

Screenshots :
![Capture](https://github.com/Curtis-Thomas/free-api-list-with-react/assets/95531539/5cbd31ff-b961-4f58-9cd1-59be1a282751)

Related Links
https://deploy-preview-117--tangerine-seahorse-5cf0e7.netlify.app/GeocodingDash

**Comment by vikki9121** [comment]
Hi @Curtis-Thomas, please assign this issue to me. I am working on it.
