### ISSUE TITLE
Good First Issue - Add Color Lovers API page

### ISSUE THREAD

**Issue by Curtis-Thomas** [Curtis-Thomas/free-api-list-with-react#12]
Phase 1: File Creation

1.1 - Locate the following:

src/api/artDesign/1ArtDesign.txt 

locate the Color Lovers link.

1.1 - Follow the hyperlink to read through the documentation and get an idea of the API usage.

1.2 - Create a file in the:

src/api/artDesign       
folder named         
     
ArtDesignColorLovers.js

1.3 - Add the following code to the file (this is just a placeholder:

```
const ArtDesignColorLovers = () => {
  return (
    <Box>
    </Box>
  );
};

export default ArtDesignColorLovers;
```

---------------------

Phase 2: Routing

2.1 - Locate the following:

src/App.js

Find the route with path="/ArtDesignDash/ArtDesignMetMuseum"

2.2 - Input on the line below:

<Route path="/ArtDesignDash/ArtDesignColorLovers" element={<ArtDesignColorLovers />} />

!!NOTE!! 

Make sure to type the component and select from the dropdown <### /> and then select from the dropdown so the file import is automatically populated 

!!NOTE!!

2.3 - Locate the following:

src/api/artDesign/artDesign1Dash.js

2.4 - Add the following component below the closing /> of the last Btn Routing:

 <BtnRouting
          btnName="Color Lovers"
          navigateTo="ArtDesignColorLovers"
          backgroundColor="#0077ba"
          textColor="white"
        />

---------------------

Phase 3: Content

3.1 - Locate the following (file you made):

src/api/artDesign/ArtDesignColorLovers.js

3.2 - Add the following code:

```
import { Box } from "@mui/material";
import BoxApiInfo from "../../core/main/BoxApiInfo";
import Endpoints from "../../core/main/Endpoints";
import BoxTestCrud from "../../tools/BoxTestCrud";
import NavBar from "../../core/main/navigation/NavBar";

const ArtDesignColorLovers = () => {
  return (
    <Box>
      <NavBar link="/###" route2="/###" />
      <Box>
        <BoxTest />
        <BoxApiInfo baseEndpoint="" />
        <Endpoints header="GET" endpoint="/" />
        <Endpoints
          header="GET"
          endpoint="/"
          description="/"
        />
      </Box>
    </Box>
  );
};

export default ArtDesignColorLovers;
```

3.3 - Add the base endpoint (found on the API site documentation)

3.4 - Add the endpoints (add extra components if there are more than 1)

3.5 - Test the functionality

4: Delete the link you used from the Txt file (To keep track of what is left to add)

Have Fun :)

**Comment by somenisco** [comment]
Hi @Curtis-Thomas ,

I want to work on this issue but I'm new to open source contribution. I'm excited to contribute and make a positive impact.
I have a few questions regarding the issue and ensure I'm on the right track:
1. Do I need to add a new route to Color Lovers api page in the ArtDesignDash ?
2. Just Like the ArtDesignEmojiHub.js I need to make a ArtDesignColorLovers.js file with required implementation ?
3. The text file contains the baseendpoint for the color lovers api link so what are the endpoints do i need to implement for it and with what type of request ?

I'm looking forward to your response and guidance.

Thank You :)

**Comment by Curtis-Thomas** [comment]
hi @somenisco and welcome! 

I need to write these instructions because they are not very clear at the moment.

Give me a short while and I will have an updated version of the instructions

**Comment by Curtis-Thomas** [comment]
@somenisco the instructions are updated now, have a try and let me know if you need anything, good luck :)!

**Comment by somenisco** [comment]
Thank you so much @Curtis-Thomas. I'll begin working on it and will seek your guidance during the process.

**Comment by somenisco** [comment]
![image](https://github.com/Curtis-Thomas/free-api-list-with-react/assets/79037839/49848922-d03a-46b1-bd7b-72d9ceee23a1)
![image](https://github.com/Curtis-Thomas/free-api-list-with-react/assets/79037839/55e00380-ef9b-4c14-9223-c3c5dd39e5a1)

Hi @Curtis-Thomas ,
I'm facing a issue here on getting response. I have tried with postman its working. So, guide me on this.

Thank You :)

**Comment by Curtis-Thomas** [comment]
@somenisco ahh this could be a problem. This means the api has set up a list of allowed URL's to access its resources. I had a quick look to see a solution but could not find an answer yet. 
It looks like postman is going through cloudflare proxy, so that could be somthing to look into.

But if you want to test another API on the list and add that instead. We can come back to this one at a later date.

But good work for getting that far :)

I will be away from the desk now, speak soon!

**Comment by somenisco** [comment]
@Curtis-Thomas  you are right proxy can be the solution for this. 

I checked with another issue #20 Gutendex api page and the api is working it seems. So, can i work on that issue?

Thank You :)
