### ISSUE TITLE
Change Footer Text Color

### ISSUE THREAD

**Issue by Curtis-Thomas** [Curtis-Thomas/free-api-list-with-react#123]
The Footer text color is currently clashing with the background and is not easily readable:

![image](https://github.com/Curtis-Thomas/free-api-list-with-react/assets/83663235/50d0db79-96ab-485b-b9af-104072e7af01)

Update the color to be more user friendly.

**Comment by parag477** [comment]
I want to work on this. Can you assign this to me?

**Comment by Curtis-Thomas** [comment]
@parag477 could you use the theme color when changing please so it is responsive to the theme changing options

**Comment by Curtis-Thomas** [comment]
@parag477 I just completed this
