### ISSUE TITLE
Style: add theme coloring to Finance dash

### ISSUE THREAD

**Issue by Curtis-Thomas** [Curtis-Thomas/free-api-list-with-react#127]
Currently, 
Finance1Dash.js
does not have a background color.

Using 
Events1.Dash.js
as a template, add the theme color to the background 

### Step 1 - Clone Repo, I find GitHub desktop the easiest to use.

![image](https://github.com/Curtis-Thomas/free-api-list-with-react/assets/83663235/2cf95a82-f6ff-42ac-ad1b-c866e03b2bcf)

### Step 2 - Open a Terminal and run the command:

`npm install`

![image](https://github.com/Curtis-Thomas/free-api-list-with-react/assets/83663235/e362fb02-a429-484c-958b-f2eb951d7bc9)

### Step 3 - Locate files:

src/api/finance/Finance1Dash.js

### Step 4 - Locate to use as reference:

src/api/events/Events1Dash.js

### Step 7 - Add 
`  sx={{
        flexGrow: 1,
        backgroundColor: theme.palette.background.default,
        minHeight: "110vh",}}`  
to the box component
      
### Step 12 - `git push`

**Comment by SoyeonL** [comment]
@Curtis-Thomas I followed the above instructions and made a pull request addressing this, please check it out.
