### ISSUE TITLE
Style: add theme coloring to FoodDrink dash

### ISSUE THREAD

**Issue by Curtis-Thomas** [Curtis-Thomas/free-api-list-with-react#128]
Currently, 
FoodDrink1Dash.js
does not have a background color.

Using 
Events1.Dash.js
as a template, add the theme color to the background 

### Step 1 - Clone Repo, I find GitHub desktop the easiest to use.

![image](https://github.com/Curtis-Thomas/free-api-list-with-react/assets/83663235/2cf95a82-f6ff-42ac-ad1b-c866e03b2bcf)

### Step 2 - Open a Terminal and run the command:

`npm install`

![image](https://github.com/Curtis-Thomas/free-api-list-with-react/assets/83663235/e362fb02-a429-484c-958b-f2eb951d7bc9)

### Step 3 - Locate files:

src/api/foodDrink/FoodDrink1Dash.js

### Step 4 - Locate to use as reference:

src/api/events/Events1Dash.js

### Step 7 - Add 
`  sx={{
        flexGrow: 1,
        backgroundColor: theme.palette.background.default,
        minHeight: "110vh",}}`  
to the box component
      
### Step 12 - `git push`

**Comment by TumiMoshou** [comment]
Hi, I am looking to contribute to my first open source project and wanted to know if I could work on this issue if it is still available?

**Comment by Curtis-Thomas** [comment]
hi @TumiMoshou sorry, this has been resolved already. But the Phone dash also needs the same changes if you would be interested in applying the same to that dash?

**Comment by TumiMoshou** [comment]
@Curtis-Thomas, yes please I would like to work on the Phone Dash

**Comment by TumiMoshou** [comment]
@Curtis-Thomas I wanted to get started, however, I wanted to make sure that I am doing the right thing. After looking through the project overview, I just wanted some clarification. Could you please provide more information about the "Phone dash" mentioned in your message?
Is the "Phone dash" a specific component or feature within the project?
What functionalities or APIs are related to the "Phone dash"?

**Comment by SuyashOP-2** [comment]
One more issue is regarding the responsiveness of the website !!

**Comment by Curtis-Thomas** [comment]
> One more issue is regarding the responsiveness of the website !!

Can you be more specific?
