### ISSUE TITLE
Text overflow 

### ISSUE THREAD

**Issue by jeevikasirwani** [Curtis-Thomas/free-api-list-with-react#147]
Issue Template
Description
on pages like anime,social ,art&design and few more  have cards in which the text is not aligned properly 

Expected Behavior
The text should be completely inside block with margin and padding.

Current Behavior
text overflow

Screenshots (if applicable)
![image](https://github.com/Curtis-Thomas/free-api-list-with-react/assets/83456541/656258a8-5f51-4398-b371-2344f69f231d)

Related Links
https://freeapilist.com/ArtDesignDash
https://freeapilist.com/AnimeDash
https://freeapilist.com/GeocodingDash

**Comment by Curtis-Thomas** [comment]
@jeevikasirwani Thanks, I just made some changes to the layout to give each more space, does this look ok now?

**Comment by jeevikasirwani** [comment]
definitely bettter!
