### ISSUE TITLE
Keep Background color same for all pages

### ISSUE THREAD

**Issue by jeevikasirwani** [Curtis-Thomas/free-api-list-with-react#148]
Issue Template
Description
few pages with 0 api have white background and few have black so keeping one color would make it better.

Screenshots (if applicable)
![image](https://github.com/Curtis-Thomas/free-api-list-with-react/assets/83456541/afcc6ac6-19b9-479d-8990-382050123daa)
![image](https://github.com/Curtis-Thomas/free-api-list-with-react/assets/83456541/43116b5d-cdea-47c5-a595-0060b875771a)

Link to webpage
https://freeapilist.com/TrackingDash
https://freeapilist.com/CryptocurrencyDash

**Comment by Curtis-Thomas** [comment]
@jeevikasirwani thanks, just did some changes to the css and removed currently empty categories should have fixed this :D
