### ISSUE TITLE
Good First Issue - Add Met Museum API

### ISSUE THREAD

**Issue by Curtis-Thomas** [Curtis-Thomas/free-api-list-with-react#18]
Phase 1: File Creation

1.1 - Locate the following:

src/api/artDesign/1ArtDesign.txt 

locate the Met Museum link.

1.1 - Follow the hyperlink to read through the documentation and get an idea of the API usage.

1.2 - Create a file in the:

src/api/artDesign       
folder named         
     
ArtDesignMetMuseum.js

1.3 - Add the following code to the file (this is just a placeholder:

```
const ArtDesignMetMuseum = () => {
  return (
    <Box>
    </Box>
  );
};

export default ArtDesignMetMuseum;
```

---------------------

Phase 2: Routing

2.1 - Locate the following:

src/App.js

Find the route with path="/ArtDesignDash/ArtDesignEmojiHub"

2.2 - Input on the line below:

<Route path="/ArtDesignDash/ArtDesignMetMuseum" element={<ArtDesignMetMuseum />} />

!!NOTE!! 

Make sure to type the component and select from the dropdown <### /> and then select from the dropdown so the file import is automatically populated 

!!NOTE!!

2.3 - Locate the following:

src/api/artDesign/artDesign1Dash.js

2.4 - Add the following component below the closing /> of the last Btn Routing:

 <BtnRouting
          btnName="Met Museum"
          navigateTo="ArtDesignMetMuseum"
          backgroundColor="#0077ba"
          textColor="white"
        />

---------------------

Phase 3: Content

3.1 - Locate the following (file you made):

src/api/artDesign/ArtDesignMetMuseum.js

3.2 - Add the following code:

```
import { Box } from "@mui/material";
import BoxApiInfo from "../../core/main/BoxApiInfo";
import Endpoints from "../../core/main/Endpoints";
import BoxTest from "../../core/main/BoxTestCrud";
import NavBar from "../../core/main/navigation/NavBar";

const ArtDesignMetMuseum = () => {
  return (
    <Box>
      <NavBar link="/###" route2="/###" />
      <Box>
        <BoxTest />
        <BoxApiInfo baseEndpoint="" />
        <Endpoints header="GET" endpoint="/" />
        <Endpoints
          header="GET"
          endpoint="/"
          description="/"
        />
      </Box>
    </Box>
  );
};

export default ArtDesignMetMuseum;
```

3.3 - Add the base endpoint (found on the API site documentation)

3.4 - Add the endpoints (add extra components if there are more than 1)

3.5 - Test the functionality

4: Delete the link you used from the Txt file (To keep track of what is left to add)

Have Fun :)

**Comment by snehachitre-apps** [comment]
i would like to work on this, please

**Comment by Curtis-Thomas** [comment]
@snehachitre-apps sure!

Let me know if you need anything, and could you make notes on how clear the instructions are and which bits need more information so I can improve them :)

**Comment by snehachitre-apps** [comment]
sure ! i will , also, this is my first contribution so please be patient with me :)  i will try to finish it as soon as possible.

**Comment by snehachitre-apps** [comment]
https://github.com/Curtis-Thomas/free-api-list-with-react/pull/46

**Comment by snehachitre-apps** [comment]
https://github.com/Curtis-Thomas/free-api-list-with-react/pull/47 

added as contributor.  thank you very much for giving me a chance.  would love to contribute more later.

**Comment by Curtis-Thomas** [comment]
feel free to raise an issue for any of the API's that you would like to add, they are stored in the text files :)
