### ISSUE TITLE
Good First Issue - Add Gutendex API Page

### ISSUE THREAD

**Issue by Curtis-Thomas** [Curtis-Thomas/free-api-list-with-react#20]
Phase 1: File Creation

1.1 - Locate the following:

src/api/books/1Books.txt 

locate the Gutendex link.

1.1 - Follow the hyperlink to read through the documentation and get an idea of the API usage.

1.2 - Create a file in the:

src/api/books folder named BooksGutendex.js

1.3 - Add the following code to the file (this is just a placeholder:

```
const BooksGutendex = () => {
  return (
    <Box>
    </Box>
  );
};

export default BooksGutendex;
```

---------------------

Phase 2: Routing

2.1 - Locate the following:

src/App.js

2.2 - Identify the correct place to insert (Try and group with others in its category:

`<Route path="/books/BooksGutendex" element={<BooksGutendex />} />`

!!NOTE!! 

Make sure to type the component and select from the dropdown `<BooksGutendex/>` and then select from the dropdown so the file import is automatically populated 

!!NOTE!!

2.3 - Locate the following:

src/api/books/Books1Dash.js

2.4 - Add the following component below the closing /> of the last Btn Routing:

```
 <BtnRouting
          btnName="Gutendex"
          navigateTo="BooksGutendex"
          backgroundColor="#0077ba"
          textColor="white"
        />
```

---------------------

Phase 3: Content

3.1 - Locate the following (file you made):

src/api/books/BooksGutendex.js

3.2 - Add the following code:

```
import { Box } from "@mui/material";
import BoxApiInfo from "../../core/main/BoxApiInfo";
import Endpoints from "../../core/main/Endpoints";
import BoxTest from "../../core/main/BoxTestCrud";
import NavBar from "../../core/main/navigation/NavBar";

const BooksGutendex = () => {
  return (
    <Box>
      <NavBar link="/###" route2="/###" />
      <Box>
        <BoxTest />
        <BoxApiInfo baseEndpoint="" />
        <Endpoints header="GET" endpoint="/" />
        <Endpoints
          header="GET"
          endpoint="/"
          description="/"
        />
      </Box>
    </Box>
  );
};

export default BooksGutendex;
```

3.3 - Add the base endpoint (found on the API site documentation)

3.4 - Add the endpoints (add extra components if there are more than 1)

3.5 - Test the functionality

4: Delete the link you used from the Txt file (To keep track of what is left to add)

Have Fun :)

**Comment by Curtis-Thomas** [comment]
@somenisco sure, I think the only thing that is outdated on these instructions is the import statement for the rest box, refer to the new instructions for this.

**Comment by somenisco** [comment]
Thank You @Curtis-Thomas.

**Comment by somenisco** [comment]
Hi @Curtis-Thomas , I have implemented this API. Shall I put a PR for this?

**Comment by Curtis-Thomas** [comment]
@somenisco I'm away from my screen for a while, but I will have a look as soon as I'm back online :)

**Comment by somenisco** [comment]
![image](https://github.com/Curtis-Thomas/free-api-list-with-react/assets/79037839/eceae00c-0edd-4808-b38c-5949bf4606b5)

@Curtis-Thomas I'm getting this error while trying to push the new branch. I need your assistance in this.
Thank You :)
