### ISSUE TITLE
apply style guide - Navbar

### ISSUE THREAD

**Issue by jibranabsarulislam** [Curtis-Thomas/free-api-list-with-react#28]
Description
style navbar according to style guide (wip)

Expected Behavior
cosmetic changes; function unchanged

Contribution Opportunity
style navbar via css file? could open issue tree of moving inline styles to modular css files

**Comment by Curtis-Thomas** [comment]
Feel free to use your preferred method.

The general styling should be focused on easy functionality and accessibility.
