### ISSUE TITLE
add: Documentation <GettingStarted /> Content

### ISSUE THREAD

**Issue by Curtis-Thomas** [Curtis-Thomas/free-api-list-with-react#31]
Populate the following component:

src/documentation/GettingStartedContent.js

This section should include:

Outline the steps needed to set up the project.

Explain how to run the project locally.

Provide a few simple examples demonstrating how to use the project.

Address common issues or errors that users might encounter during the setup process.

Encourage users to contribute to the project.

have fun :)

**Comment by MamathaKarapanahalli** [comment]
Hi, 

I am a newbie to GitHub and technical documentation. 
I am looking for beginner's projects to which I can contribute. 

I took a look at this one and also have installed all the necessary prerequisites. 
I would love to explore further and contribute to this project. 

However, I have one question:
-I tried to run the project using the link https://curtis-thomas.github.io/ 
 For every API, it asks for the base URL and endpoint. Where do I get them to run the APIs? 

Kindly clarify this. It would help me familiarize myself with the project and contribute to its documentation. 

Thanks,
Mamatha

**Comment by Curtis-Thomas** [comment]
Hi @MamathaKarapanahalli and welcome!

The current live example is reachable through:

`https://curtis-thomas.github.io/free-api-list-with-react/`

Currently, only the categories with a blue button background have any content added.

![base url](https://github.com/Curtis-Thomas/free-api-list-with-react/assets/83663235/2d13e939-33e1-41f4-9100-cb46e3ae5e5e)


The Base URL and Endpoint can be found below the text box.

Let me know if this is clear, 
and if you want this issue assigned to you please also let me know :)

**Comment by MamathaKarapanahalli** [comment]
Hi @Curtis-Thomas ,

I would like to mention that as JS is new to me, it might take a bit longer than usual to learn and complete the work. 
If that's fine, please assign it to me. 

Thanks,
Mamatha

**Comment by Curtis-Thomas** [comment]
@MamathaKarapanahalli there is no rush.

And thank you :)!

**Comment by MamathaKarapanahalli** [comment]
Hi @Curtis-Thomas ,

I tried to add a test change to the getting started content file to see my changes reflect on the git hub page created using my local repository - MamathaKarapanahalli](https://github.com/MamathaKarapanahalli

It initially didn't. 

I searched online and did some additional changes to make it happen: 
1. In the package.json file (https://github.com/MamathaKarapanahalli/free-api-list-with-react/blob/main/package.json): I changed the link to homepage. 
2. In the readme.md file (https://github.com/MamathaKarapanahalli/free-api-list-with-react/blob/main/README.md); I changed the link under "Live Demo" section to point it to my git hub page. New link that I put in - https://mamathakarapanahalli.github.io/free-api-list-with-react/.

Even after doing these changes, when I click on live demo link it takes me to your repository git hub page.. do you know why this could happen?

Thanks,
Mamatha

**Comment by Curtis-Thomas** [comment]
Hi @MamathaKarapanahalli if you have node js installed on your machine and after you have the repo cloned and stored locally.

Using a command line, use the:

 'npm start'

 command which will run your version of the project :)
