### ISSUE TITLE
add: favicon to the project - Good First Issue

### ISSUE THREAD

**Issue by Curtis-Thomas** [Curtis-Thomas/free-api-list-with-react#35]
This task is great for someone with an eye for design. 

Create a favicon for the project to use, the design should be inspired by our stack:
-Github
-React
-MaterialUI
-API's

Then delete the current favicon:

build/favicon.ico

and upload the replacement using the same file name:

favicon.ico

And place it in the same folder.

Have fun :)

**Comment by Shubham1450** [comment]
I want to work on this issue can you please assign it to me. @Curtis-Thomas

**Comment by Khushi2402** [comment]
Is the issue still open? If yes, can you assign it to me as well? I would like to work on it.

**Comment by Curtis-Thomas** [comment]
@Khushi2402 this is still open.

@Shubham1450 are you still planning on doing this?

**Comment by Anubhav-Chauhan3367** [comment]
Is this issue still open? If it is, please assign it to me.
