### ISSUE TITLE
Create Advanced CRUD Api Test Box Component

### ISSUE THREAD

**Issue by Curtis-Thomas** [Curtis-Thomas/free-api-list-with-react#4]
Description

Using the current CRUD test box component. Create an advanced version that can offer more customization to the requests.

**Comment by pchawlaji** [comment]
@Curtis-Thomas would you mind if I add some comments to the existing code as well

**Comment by pchawlaji** [comment]
@Curtis-Thomas is it ok with you if you can assign this issue in my name.

**Comment by Curtis-Thomas** [comment]
> @Curtis-Thomas would you mind if I add some comments to the existing code as well

Raise an issue for this :)

**Comment by Curtis-Thomas** [comment]
> @Curtis-Thomas is it ok with you if you can assign this issue in my name.

For the advanced version, could it be made as a whole new component with a different name? Then the relevant component can be inserted whenever it is needed.

**Comment by pchawlaji** [comment]
> > @Curtis-Thomas would you mind if I add some comments to the existing code as well
> 
> Raise an issue for this :)

Thank you.. I have raised new issue for this.
https://github.com/Curtis-Thomas/free-api-list-with-react/issues/24
