### ISSUE TITLE
Style: Remove hover effect from <AdvancedBoxTestCrud /> Btn - Good First Issue

### ISSUE THREAD

**Issue by Curtis-Thomas** [Curtis-Thomas/free-api-list-with-react#41]
Navigate to:

src/tools/AdvancedBoxTestCrud

The Fetch Button has hover effect styling added by default. Remove the styling to be similar in look to `<BoxTestCrud />`

**Comment by anjali29singh** [comment]
@vishalpawarR  i have already made the pull request

**Comment by Curtis-Thomas** [comment]
@vishalpawarR sorry this issue has been resolved, I will try and put some more up. 

If you find anything that could be improved, feel free to raise an issue and after triage, I can assign it :)
