### ISSUE TITLE
Style: Remove hover effect from <BoxTestImg /> Btn - Good First Issue

### ISSUE THREAD

**Issue by Curtis-Thomas** [Curtis-Thomas/free-api-list-with-react#42]
Navigate to:

src/tools/BoxTestImg.js

The Fetch Button has hover effect styling added by default. Remove the styling to be similar in look to `<BoxTestCrud />`

**Comment by anjali29singh** [comment]
can you assign this issue to me

**Comment by anjali29singh** [comment]
Task is to remove hover effect from only fetch button ?

**Comment by Curtis-Thomas** [comment]
@anjali29singh 

Correct, as seen below:

![btn before after](https://github.com/Curtis-Thomas/free-api-list-with-react/assets/83663235/32924d45-3b3d-4279-8c81-17ffa9a157d7)

**Comment by vishalpawarR** [comment]
@Curtis-Thomas Hey can you please provide me the proper steps for reproducing the issue so that I can help you with this quickly? I can see the button and the file button how do I reproduce the issue?

**Comment by Curtis-Thomas** [comment]
Sorry for being unclear.  The best place to see the issue is on the live page:

https://curtis-thomas.github.io/free-api-list-with-react/

and navigating to the tools page using the icon on the top right, the issue is the styling of the button on hover. 

![hover btn](https://github.com/Curtis-Thomas/free-api-list-with-react/assets/83663235/2690f720-1d26-4303-94a2-d2d920836fcb)

The style should be set to default the same as with the regular CRUD testing box as seen below with no effect on hover:


![desired btn hover style](https://github.com/Curtis-Thomas/free-api-list-with-react/assets/83663235/c20b8db2-b1be-4dab-8b94-7c028c87eeb0)


I  will be away from my pc until tomorrow, but if you have any other questions just let me know :)
