### ISSUE TITLE
style: Improve layout and responsiveness of <Main /> - Good First Issue

### ISSUE THREAD

**Issue by Curtis-Thomas** [Curtis-Thomas/free-api-list-with-react#43]
Refer to the images below, 

Update:

src/core/main/BtnRouting.js

and

src/core/main/Main.js

To resolve the following issues:

Button size inconsistent on mobile view
![BtnRouting Mobile View](https://github.com/Curtis-Thomas/free-api-list-with-react/assets/83663235/d2b391d4-a3e6-444b-9e65-e787ba0bc3c7)

and bad layout on Desktop view:

![btnRouting Desktop view](https://github.com/Curtis-Thomas/free-api-list-with-react/assets/83663235/f12d2ac1-f7c1-4bec-bf28-00f99c681379)

The project uses React Js

https://react.dev/

and Material UI:

https://mui.com/

Let me know if you would like to be assigned this :)

**Comment by kotkaravishkar** [comment]
Can I work on it ?

**Comment by sheryarking5** [comment]
@Curtis-Thomas can you explain more about desktop layout issue.i want to work on these issues

**Comment by Curtis-Thomas** [comment]
@kotkaravishkar @sheryarking5 would it be ok if you both worked on this as a shared issue with collaboration?

The main problem is the columns that are holding the buttons are housed in a <Box> which is being used as a container. The styling for this is wrong.

This is leading to them being pushed to the left side of the screen instead of being displayed with equal spacing to the left and right. 

This issue carries over to mobile as well.

The solution could be to add a media query for the mobile view and add flex styling for the desktop view. 

The end goal is to have the layout look professional and uniform.

**Comment by SheryarDev** [comment]
> 

Yeah sure i can collaborate.Thanks for your explanation
