### ISSUE TITLE
[Suggestiion] Add IP2Location.io API Under api/geocoding

### ISSUE THREAD

**Issue by ip2location** [Curtis-Thomas/free-api-list-with-react#55]
We would like to propose the IP2Location.io API from https://www.ip2location.io for listing under api/geocoding.

Thank you.

**Comment by Curtis-Thomas** [comment]
Hello, thank you for getting in touch.

Does IP2Location.io offer a free-to-use mode with no sign-up required?

**Comment by ip2location** [comment]
Hi @Curtis-Thomas 

Our API requires sign-up. It offers free 30K queries per month.
