### ISSUE TITLE
Add Favicon Icon

### ISSUE THREAD

**Issue by Curtis-Thomas** [Curtis-Thomas/free-api-list-with-react#56]
Issue Title: Add Favicon Icon

Issue Description:
We currently don't have a favicon icon for our project, and it would be great to have one to improve the user experience and brand recognition. Favicon icons are those tiny icons that appear in browser tabs and bookmarks, making it easier for users to identify our project.

Tasks:

 Create a favicon icon (usually a 16x16 or 32x32 pixel image).
 Add the favicon image to the project's root directory (e.g., as favicon.ico).
 Update the HTML templates to include the favicon in the <head> section of all pages. You can use the <link> tag to specify the favicon's location.

Acceptance Criteria:

 The favicon icon is visually appealing and represents our project well.
 The favicon is added to the project's root directory.
 The HTML templates have been updated to include the favicon using the <link> tag.

Additional Information:
If you have any design ideas or specific requirements for the favicon, please provide them here. Otherwise, our contributors can use their creativity to design a suitable favicon for the project.

**Comment by SUE-GIA** [comment]
Hey, I would like to give this one a try as well!

**Comment by SUE-GIA** [comment]
I got a .svg preview ready of the favicon. Do you want me to PR?
