### ISSUE TITLE
Enhance Styling of BtnRouting Button

### ISSUE THREAD

**Issue by Curtis-Thomas** [Curtis-Thomas/free-api-list-with-react#58]
Issue Title: Enhance Styling of BtnRouting Button

Issue Description:
The styling of the BtnRouting button component can be improved to enhance its visual appeal and user experience, especially considering the use of Material-UI.

Tasks:

 Review and update the Material-UI styles applied to the button.
 Adjust padding, font size, or add hover effects for a more polished appearance using Material-UI styles.
Acceptance Criteria:

 The button has improved Material-UI styling that enhances its visual appeal.
 The button looks more appealing on hover.

**Comment by pepoloco** [comment]
Hey can i take this one also

**Comment by Curtis-Thomas** [comment]
@pepoloco so sorry, I only just realised this was assigned to you

**Comment by pepoloco** [comment]
It’s okay
