### ISSUE TITLE
Refactor BtnRouting Component for Improved Code Structure

### ISSUE THREAD

**Issue by Curtis-Thomas** [Curtis-Thomas/free-api-list-with-react#61]
Issue Title: Refactor BtnRouting Component for Improved Code Structure

Issue Description:
Consider refactoring the BtnRouting component for better code organization, readability, and maintainability while taking into account the use of Material-UI.

Tasks:

 Review the component's code and identify areas for improvement.
 Refactor the component if necessary, breaking it into smaller, more manageable functions or components while adhering to Material-UI styling guidelines.
Acceptance Criteria:

 The component's code is better organized and more readable.
 The refactor improves code maintainability, considering Material-UI styling.

**Comment by pravintargaryen** [comment]
@Curtis-Thomas assign this issue to me

**Comment by Curtis-Thomas** [comment]
@pchawlaji done! let me know if you need anything :)

**Comment by Curtis-Thomas** [comment]
BtnRouting has been replaces, I will close this issue
