### ISSUE TITLE
Write Unit Tests for BtnRouting Component

### ISSUE THREAD

**Issue by Curtis-Thomas** [Curtis-Thomas/free-api-list-with-react#62]
Issue Title: Write Unit Tests for BtnRouting Component

Issue Description:
Create unit tests for the BtnRouting component to ensure its functionality is correct and robust, considering its integration with React.js and Material-UI.

Tasks:

 Set up a testing environment using a testing framework like Jest.
 Write unit tests to cover various aspects of the BtnRouting component's behavior, taking into account React.js and Material-UI components.
Acceptance Criteria:

 Unit tests for the component are written and pass successfully.
 Test coverage adequately checks the component's functionality, including interactions with React.js and Material-UI components.

**Comment by pepoloco** [comment]
I want to take this

**Comment by pepoloco** [comment]
Give this to somebody else , there is a problem with  | import GitHubButton from "react-github-btn"; 
It's marking it as an error , when I try to do a JEST test to the buttons and i have the latest version of JEST and GitHubButton.
