### ISSUE TITLE
Enhance Styling of BoxApiInfo Component

### ISSUE THREAD

**Issue by Curtis-Thomas** [Curtis-Thomas/free-api-list-with-react#65]
Issue Title: Enhance Styling of BoxApiInfo Component

Issue Description:
The styling of the BoxApiInfo component can be improved to enhance its visual appeal and user experience.

Tasks:

 Review and update the Material-UI styles applied to the component.
 Adjust margins, padding, or add styling enhancements for a more polished appearance.
Acceptance Criteria:

 The component has improved Material-UI styling that enhances its visual appeal.
 The component looks more appealing and well-structured.

**Comment by Latish705** [comment]
@Curtis-Thomas I would like to do this please assign it to me
