### ISSUE TITLE
Enhance Styling of Header Component

### ISSUE THREAD

**Issue by Curtis-Thomas** [Curtis-Thomas/free-api-list-with-react#69]
Issue Title: Enhance Styling of Header Component

Issue Description:
The styling of the Header component can be improved to enhance its visual appeal and user experience.

Tasks:

 Review and update the Material-UI styles applied to the component.
 Adjust margins, padding, or add styling enhancements for a more polished appearance.
Acceptance Criteria:

 The component has improved Material-UI styling that enhances its visual appeal.
 The component looks more appealing and well-structured.

**Comment by SUE-GIA** [comment]
Hey, can I try to solve this?

**Comment by Curtis-Thomas** [comment]
@SUE-GIA yeah you can :)!
