### ISSUE TITLE
Improve Accessibility of Header Component

### ISSUE THREAD

**Issue by Curtis-Thomas** [Curtis-Thomas/free-api-list-with-react#70]
Issue Title: Improve Accessibility of Header Component

Issue Description:
Ensure that the Header component is accessible to users with disabilities and can be interacted with using a keyboard and screen reader.

Tasks:

 Add appropriate ARIA attributes and labels to the components within Header.
 Test the component's accessibility with keyboard navigation and screen reader tools.
Acceptance Criteria:

 The component is accessible to users with disabilities.
 Keyboard navigation and screen reader usage work as expected with the component.

**Comment by eshan-one** [comment]
Hey @Curtis-Thomas I would like to work on this issue. Please can you assign me this?
