### ISSUE TITLE
Update Documentation in Header Component

### ISSUE THREAD

**Issue by Curtis-Thomas** [Curtis-Thomas/free-api-list-with-react#71]
Issue Title: Update Documentation in Header Component

Issue Description:
Ensure that the Header component's usage is well-documented, and add comments to improve code readability.

Tasks:

 Review the component's documentation and comments.
 Update and improve documentation where necessary.
 Add comments to clarify the purpose of different parts of the code.
Acceptance Criteria:

 The component's documentation is updated and accurate.
 Code comments enhance code readability and understanding.

**Comment by eshan-one** [comment]
Hey @Curtis-Thomas can you please assign me this issue Just wanna confirm that this issue deals with the Header.js file and I am suppose to add comments and improve code readability right?

**Comment by Curtis-Thomas** [comment]
@eshan-one I will assign, yes that is correct, comment and clean up the code only. No added functionality.

**Comment by eshan-one** [comment]
Thanks!✌
