### ISSUE TITLE
Customize the Dark Theme

### ISSUE THREAD

**Issue by Curtis-Thomas** [Curtis-Thomas/free-api-list-with-react#72]
Issue Title: Customize the Dark Theme

Issue Description:
Enhance the customization options for the dark theme to make it more flexible and user-friendly.

Tasks:

 Review the existing dark theme configuration.
 Identify areas where customization options can be added, such as additional color choices or typography variations.
 Implement these customization options in the theme.
Acceptance Criteria:

 Users can easily customize the dark theme by adjusting colors or typography.
 The customization options are well-documented for users.

**Comment by venkataraviraja5** [comment]
i would like to work on this issue can you please assign to me @Curtis-Thomas

**Comment by Curtis-Thomas** [comment]
@venkataraviraja5 done, let me know if you need anything :)

**Comment by venkataraviraja5** [comment]
dark mode feature is working fine,can you please explain more about this

**Comment by Curtis-Thomas** [comment]
@venkataraviraja5 dark mode is working but needs some tweaking still, check through for anything that needs to be changed, such as this button hover colors:


![image](https://github.com/Curtis-Thomas/free-api-list-with-react/assets/83663235/2db5a27d-fa91-414c-9791-ef79d9ea80d8)

**Comment by venkataraviraja5** [comment]
@Curtis-Thomas  can i change to white color on hover
