### ISSUE TITLE
Update Header Text to "Free API List"

### ISSUE THREAD

**Issue by Curtis-Thomas** [Curtis-Thomas/free-api-list-with-react#73]
Issue Title: Update Header Text to "Free API List"

Issue Description:
The text "FAR" in the header of the application should be updated to "Free API List" for clarity and to better represent the purpose of the application.

Tasks:

 Locate the text "FAR" in the Header component.
 Replace the text "FAR" with "Free API List."
Acceptance Criteria:

 The text in the header is updated to "Free API List."
 The updated text is correctly displayed in the application header.

**Comment by pepoloco** [comment]
Hey can i take this

**Comment by Curtis-Thomas** [comment]
@pepoloco yeah sure :)!

**Comment by Curtis-Thomas** [comment]
Complete.
