### ISSUE TITLE
Add a Dynamic Year Update Functionality to the Footer Component

### ISSUE THREAD

**Issue by Curtis-Thomas** [Curtis-Thomas/free-api-list-with-react#77]
Currently, the footer component has a static copyright year, which means it needs to be manually updated every year. To improve maintainability, this beginner-friendly issue involves adding dynamic year update functionality to the footer component. This task will automatically update the copyright year to the current year, ensuring that the footer remains up to date without manual intervention.

Tasks:

Modify the Footer component to dynamically display the current year using JavaScript's Date object.
Ensure the displayed year updates automatically when the year changes.
Verify that the dynamic date functionality is compatible with server-side rendering (if applicable).
Skills Required:

Basic understanding of React and JavaScript
Familiarity with JSX syntax
Good First Issue: Yes

Mentorship:
We will provide support for anyone who needs guidance on JavaScript's Date object and its use within a React component. This issue offers a great way to practice using dynamic expressions in JSX.

Additional Resources:

[JavaScript Date Reference](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date)
[React Documentation](https://reactjs.org/docs/getting-started.html)
Feel free to comment on this issue if you need any help or have any questions. Our team is here to ensure your contribution process is smooth and educational!

**Comment by acelanoit** [comment]
Hello Curtis-Thomas, would it be ok if I took care of this? Can you please assign the issue to me?

**Comment by Curtis-Thomas** [comment]
@acelanoit done :)
