### ISSUE TITLE
Standardize Layout and Populate Content for Dictionary API Pages

### ISSUE THREAD

**Issue by Curtis-Thomas** [Curtis-Thomas/free-api-list-with-react#80]
Following the layout established in the AnimalsCataas page, this task involves creating a standardized layout for each Dictionary API page listed in the Dictionaries array. Each page should provide detailed information about its respective API, utilizing a consistent layout to enhance user experience and ease of navigation. This beginner-friendly task is focused on ensuring consistency in layout and enriching the content for each API.

Tasks:

Implement a similar layout to the AnimalsCataas page for each Dictionary API page, including the NavBar, BoxApiInfo, Endpoints, and any other relevant components.
Populate each page with API-specific information, including the base endpoint URL and descriptions for available API endpoints.
Ensure that each API page provides a detailed and user-friendly description, explaining the API's purpose and functionalities.
Maintain a consistent visual and structural design across all Dictionary API pages for a cohesive user experience.
Skills Required:

Basic understanding of React and JSX.
Ability to research and compile information about different APIs.
Attention to detail to maintain consistency in layout and style across multiple pages.
Good First Issue: Yes

Mentorship:
This issue offers an opportunity to practice creating structured and informative web pages in React. We will provide guidance on layout standardization, API research, and effective communication of technical information.

Additional Context:
The goal is to create a set of standardized, informative, and visually appealing pages for each Dictionary API, making it easier for users to understand and interact with these APIs. The pages should be engaging, informative, and easy to navigate.

Contributors are encouraged to ask questions and seek support in the issue comments. Our team is dedicated to assisting new contributors and ensuring a smooth contribution process!

**Comment by pravintargaryen** [comment]
@Curtis-Thomas Assign this issue to me

**Comment by Abhay-Narayan** [comment]
@Curtis-Thomas Assign this issue to me, I would love to add more pages in dictionary api

**Comment by Curtis-Thomas** [comment]
@Abhay-Narayan @pravintargaryen

I think this will be a good issue to work on together. I would suggest posting on here to  let each other know which page you are adding to reduce overlap.

**Comment by Abhay-Narayan** [comment]
@Curtis-Thomas All of the other Api's are asking for the API keys.. can you explain how to proceed with that

**Comment by Curtis-Thomas** [comment]
@Abhay-Narayan it looks like that list has not been checked yet, you can either check them all and only use the ones that do not require api key.

I also checked through the geocoding ones today and they are useable
