### ISSUE TITLE
Automate and Dynamically Update Contributors List in the Contributors Content Component

### ISSUE THREAD

**Issue by Curtis-Thomas** [Curtis-Thomas/free-api-list-with-react#83]
The current implementation of the ContributorsContent component statically lists contributors, requiring manual updates each time a new contributor joins. This issue aims to automate the process by dynamically fetching and displaying contributor data from the project's GitHub repository. This enhancement will ensure the list stays up-to-date automatically and reduces manual maintenance. This beginner-friendly issue is a blend of frontend development and integration with GitHub's API.

Tasks:

Implement a function to fetch contributor data from the GitHub API for the project's repository.
Dynamically render each contributor's name, contribution date, and GitHub profile link using the fetched data.
Ensure error handling for API requests and display a fallback message if the data cannot be fetched.
Optionally, add features like sorting by contribution date or filtering by contribution type.
Skills Required:

Basic understanding of React and asynchronous JavaScript (e.g., fetch API, async/await).
Familiarity with consuming RESTful APIs, specifically GitHub's API.
Basic error handling in JavaScript.
Good First Issue: Yes

Mentorship:
This task offers an excellent opportunity for contributors to work with external APIs and dynamic data rendering in React. Guidance on using the GitHub API and integrating it with the React component will be provided.

Additional Context:
Automating the contributors list not only keeps the information up-to-date but also showcases the active community involvement in the project, potentially encouraging more contributions.

Contributors are encouraged to discuss their approach or seek assistance in the issue comments. Our team is committed to supporting new contributors and ensuring a smooth and educational contribution process!

**Comment by IrfanSalim** [comment]
Hey, can I take this up?

**Comment by Curtis-Thomas** [comment]
@IrfanSalim Yes, please do :D

**Comment by IrfanSalim** [comment]
Hey @Curtis-Thomas 

Is this looking fine?

![image](https://github.com/Curtis-Thomas/free-api-list-with-react/assets/109443065/7b7613b6-edbc-4503-8929-61ffba937956)
