### ISSUE TITLE
Enhance Mobile Responsiveness for Contributors Component

### ISSUE THREAD

**Issue by Curtis-Thomas** [Curtis-Thomas/free-api-list-with-react#95]
We're looking for community help to improve the mobile responsiveness of our Contributors component in the free-api-list-with-react project. This component currently uses Material UI components and is designed primarily for desktop view. We want to ensure a seamless and user-friendly experience on mobile devices as well.

Current Behavior:
The Contributors component displays a table with the columns: Name, Contributions, Last Contribution Date, and GitHub Profile.
On mobile devices, the table does not resize or reformat, leading to a cramped and hard-to-navigate interface.

Desired Behavior:
The table should be easily readable and navigable on mobile devices.
Consider reformatting the table layout, adjusting font sizes, or implementing a different UI pattern (like cards or a collapsible list) for mobile view.
Ensure that the design is consistent with the overall aesthetics of the application.

Technical Details:
The component is implemented in React.js using Material UI components.

Please make sure to adhere to the existing coding style and comment on any significant changes.

How to Get Started:
Fork the repository and set up the project locally.
Reproduce the issue by viewing the Contributors component on a mobile device or using a mobile view in your browser's developer tools.
Experiment with different UI solutions to improve the mobile experience.
Once a suitable solution is found, create a pull request with your changes.

Additional Resources:
[Material UI Documentation](https://mui.com/)
[React Documentation](https://reactjs.org/docs/getting-started.html)

We appreciate any contributions made to this project and look forward to your innovative solutions!

**Comment by NehaNihar12** [comment]
Hi @Curtis-Thomas , I am working on this issue.
