### ISSUE TITLE
Enhance and Update the CONTRIBUTING.md File for a more visually inviting and clear looking structure

### ISSUE THREAD

**Issue by Jaovitosr** [Curtis-Thomas/free-api-list-with-react#96]
### **Description**
Despite the CONTRIBUTING.md file containing valuable information even for newcomers, its visual presentation appears confusing and overwhelmed with information. Modifications to the Markdown file are deemed relevant and beneficial for the comprehensive understanding of both project users and contributors. Organizing the information into clear topics and subtopics is essential for the seamless progression of the contribution process. This will benefit not only those who have been contributing to the project for some time but also newcomers.

### **Proposed Changes:**

**- Organize Information:** Group related information into distinct and clear topics.

**- Create Subtopics:** Introduce relevant subtopics to provide more granularity.

**- Improve Visual Clarity:** Enhance the overall visual presentation for easier navigation.

**- Enhance Readability:** Ensure that the content is presented in a manner that is easy to comprehend for both experienced contributors and newcomers.

These changes aim to streamline the CONTRIBUTING.md file, making it more accessible and user-friendly. By implementing a structured approach with clear topics and subtopics, we can facilitate a better understanding of the contribution process for all users involved.

Please feel free to discuss and provide additional suggestions regarding these proposed changes.

**Comment by Jaovitosr** [comment]
I've opened the issue and am confident in my ability to handle this matter. I'm actively improving the README file and can harmonize both documents using consistent strategies and structures. Could this issue be assigned to me?

**Comment by SuyashOP-2** [comment]
Plz specify in readme about  environment variables :)
